cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
        path('', views.cart_detail, name='cart_detail'),
        path('add/<int:product_id>/', views.cart_add, name='cart_add'),
        path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
        ]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name="order_create")
         ]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
        path('', views.product_list, name='product_list'),
        path('<slug:category_slug>/', views.product_list,
             name='product_list_by_category'),
        path('<int:id>/<slug:slug>/', views.product_detail,
             name='product_detail'),
        path('<int:id>/<slug:slug>/popup', views.product_detail_popup,
             name='product_detail_popup'),
        ]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST       # ONLY POST REQUEST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # update product quantities in the cart
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                    initial={'quantity': item['quantity'],
                                             'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_home(request):
    # request.session.set_expiry(300)
    # key = request.session.session_key
    # print(key)
    request.session['first_name'] = "Mau"
    return render(request, "cart/home.html", {})

cart/templates/cart/base.html
{% extends "base.html" %}
{% load static %}

<!--CSS-->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css"  href="{% static 'css/cart.css' %}">
{% endblock stylesheets %}
<!--END_css-->

{% block content %}
    {% block cart_content %}

    {% endblock cart_content %}
{% endblock content %}

cart/templates/cart/detail.html
{% extends "cart/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block cart_content %}
<br>
<br>
<br>
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <!-- update product quantities -->
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
                <!--  - - -    -->
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
    <a href="{% url "orders:order_create" %}" class="button">
      Checkout
    </a>
  </p>
{% endblock cart_content %}